export type Mode = "artwork" | "performance" | "customization" | "screen_sync" | "audio_sync" | "blackout" | "events" | "disabled";
export type HomeDisplay = "steam" | "blackout" | "customization" | "performance" | "audio_sync" | "weather" | "controller";
export type GameDisplay = "steam" | "blackout" | "customization" | "artwork" | "performance" | "screen_sync" | "audio_sync" | "weather" | "controller";
export type DisplayPreset = "custom" | "lights-out" | "focus" | "essential" | "moderate" | "atmosphere" | "signals" | "immersive" | "immersive-plus" | "festive";
export type ValveOwnershipPolicy = "cooperative" | "downloads" | "critical";
export type ArtworkMode = "auto" | "center" | "lower" | "manual";
export type ArtworkSource = "hero" | "header" | "capsule";
export type LaunchArtworkPattern = "arpege-crossed" | "two-hands" | "legato" | "nocturne" | "crescendo"
  | "color-wipe" | "scanner" | "theater-chase" | "twinkle" | "ripple";
export type CustomizationPattern = string;
export type PerformanceMetric = "cpu" | "gpu" | "mixed";
export type PerformanceSmoothing = "responsive" | "balanced" | "smooth";
export type MixedDirection = "same" | "mirrored";
export type TemperaturePalette = "thermal" | "classic" | "icefire" | "custom";
export type CountdownColour = "cyan" | "green" | "amber" | "violet" | "white";
export type RGB = [number, number, number];
export type CompanionPriority = "stripmine" | "signalbar";
export type WeatherCondition = "clear_day" | "clear_night" | "rain" | "cloud" | "cloud_night" | "breaks" | "breaks_night" | "snow" | "storm";
export type WeatherIconStyle = "current" | "material-rounded" | "phosphor-duotone";
export interface WeatherLocation { name: string; country: string; latitude: number; longitude: number }

export type UpdatePhase = "idle" | "checking" | "up_to_date" | "available"
  | "downloading" | "verifying" | "ready" | "installing" | "restart_pending"
  | "updated" | "rolled_back" | "error" | "managed_by_decky" | "authorization_required";

export interface UpdateStatus {
  phase: UpdatePhase;
  installed_version: string;
  available_version: string;
  last_checked_at: number;
  next_check_at: number;
  notified_version: string;
  release_notes: string;
  release_url: string;
  prepared_digest: string;
  confirmation_token: string;
  rollback_version: string;
  last_result: string;
  error_category: string;
  error: string;
  auto_check: boolean;
  notifications: boolean;
  check_interval_minutes: 15 | 60 | 180 | 360 | 720 | 1440;
  channel: "stable" | "beta" | "private";
  test_build: boolean;
  private_auth_configured: boolean;
  private_auth_state: "disconnected" | "pending" | "connected" | "expired" | "error";
  private_user_code: string;
  private_verification_uri: string;
  private_auth_expires_at: number;
  private_repository: string;
}

export interface UpdateLabResult {
  scenario: "valid-package" | "checksum-mismatch" | "rollback";
  passed: boolean;
  started_at: number;
  finished_at: number;
  details: string;
  digest?: string;
  service_starts?: number;
  service_stops?: number;
  report_available: boolean;
}

export interface Status {
  version: string;
  available: boolean;
  active: boolean;
  owner: "Valve" | "GabeCubeAura";
  provider: string;
  suspension_reason: string;
  error: string;
  mode: Mode;
  default_mode: HomeDisplay | GameDisplay;
  display_override: "inherit" | GameDisplay;
  signalbar_enabled: boolean;
  onboarding_completed: boolean;
  display_preset: DisplayPreset;
  display_preset_preview: {
    active: boolean;
    preset: string;
    remaining_s: number;
    phase: "" | "Audio Sync" | "Screen Sync";
    colors: RGB[];
  };
  valve_ownership_policy: ValveOwnershipPolicy;
  led_output_calibration_mode: "follow" | "consistent";
  led_output_calibration: {
    mode: "follow" | "consistent";
    supported: boolean;
    detected_brightness: number | null;
    reference_brightness: number;
    saved_steam_brightness: number | null;
    override_active: boolean;
    startup_recovered: boolean;
  };
  light_bar_day_brightness: number;
  light_bar_brightness: {
    supported: boolean;
    control_mode: "hardware" | "rgb-fallback";
    day_brightness: number;
    night_percentage: number;
    target_brightness: number | null;
    current_output: "day" | "night" | "alert" | "valve";
    detected_brightness: number | null;
    applied_brightness: number | null;
    saved_steam_brightness: number | null;
    override_active: boolean;
    startup_recovered: boolean;
  };
  home_display: HomeDisplay;
  game_display: GameDisplay;
  current_display: HomeDisplay | GameDisplay;
  performance_metric: PerformanceMetric;
  performance_smoothing: PerformanceSmoothing;
  performance_always: boolean;
  mixed_direction: MixedDirection;
  temperature_palette: TemperaturePalette;
  temperature_custom_cool: RGB;
  temperature_custom_middle: RGB;
  temperature_custom_hot: RGB;
  artwork_mode: ArtworkMode;
  artwork_manual_y: number;
  artwork_source: ArtworkSource;
  artwork_vibrance: number;
  artwork_custom: boolean;
  artwork_default_mode: ArtworkMode;
  artwork_default_manual_y: number;
  artwork_default_source: ArtworkSource;
  artwork_default_vibrance: number;
  launch_artwork_animation_enabled: boolean;
  launch_artwork_pattern: LaunchArtworkPattern;
  launch_artwork_colour_count: 2 | 3;
  launch_artwork_duration_seconds: number;
  launch_artwork_source: ArtworkSource;
  launch_artwork_palette_mode: "artwork" | "custom";
  launch_artwork_custom_palettes: { "2": [RGB, RGB]; "3": [RGB, RGB, RGB] };
  customization_pattern: CustomizationPattern;
  customization_colour_count: 1 | 2 | 3;
  customization_colour_1: RGB;
  customization_colour_2: RGB;
  customization_colour_3: RGB;
  customization_brightness: number;
  customization_speed: number;
  customization_direction: "forward" | "reverse";
  screen_sync_style: "panorama" | "ambient";
  screen_sync_brightness: number;
  screen_sync_reactivity: "calm" | "balanced" | "fast";
  screen_sync_colour_intensity: "natural" | "vivid";
  screen_sync_black_threshold: number;
  screen_sync_ignore_black_bars: boolean;
  screen_sync_screensaver_enabled: boolean;
  audio_sync_style: "hifi-crest" | "velvet-relay" | "negative-bloom" | "stereo-lanterns"
    | "constellation" | "slow-prism" | "spectrum" | "spatial" | "bass"
    | "audio-pulse";
  audio_sync_brightness: number;
  audio_sync_reactivity: "calm" | "balanced" | "fast" | "punchy";
  audio_sync_palette: "aurora" | "ember" | "magma" | "forest" | "ice" | "copper" | "solar" | "pearl" | "glacier" | "lagoon" | "lime" | "orchid" | "plasma" | "sunset" | "deep-sea" | "silver" | "candy" | "sapphire" | "coastline" | "screen-sync" | "artwork" | "custom";
  audio_sync_home_style: Status["audio_sync_style"];
  audio_sync_home_palette: Status["audio_sync_palette"];
  audio_sync_game_style: Status["audio_sync_style"];
  audio_sync_game_palette: Status["audio_sync_palette"];
  audio_sync_lab_crest_strength: number;
  audio_sync_lab_edge_reach: number;
  audio_sync_lab_background: number;
  audio_sync_hifi_lab_enabled: boolean;
  audio_sync_home_colour_low: RGB;
  audio_sync_home_colour_middle: RGB;
  audio_sync_home_colour_high: RGB;
  audio_sync_game_colour_low: RGB;
  audio_sync_game_colour_middle: RGB;
  audio_sync_game_colour_high: RGB;
  cool_temp_c: number;
  hot_temp_c: number;
  reverse_led_order: boolean;
  parental_countdown_enabled: boolean;
  countdown_colour: CountdownColour;
  countdown_full_bar_minutes: 0 | 60 | 120 | 180 | 240;
  countdown_dark_edge_compensation: number;
  free_timer_minutes: number;
  events_enabled: boolean;
  event_notifications_enabled: boolean;
  event_achievements_enabled: boolean;
  event_screenshots_enabled: boolean;
  event_recording_enabled: boolean;
  recording_marker_isolation: boolean;
  event_notification_variant: string;
  event_achievement_variant: string;
  event_screenshot_variant: string;
  controller_battery_display: "off" | "home" | "game" | "everywhere";
  controller_charging_mode: "off" | "brief" | "continuous-home" | "continuous-everywhere";
  controller_charging_display: "off" | "home" | "everywhere";
  controller_alert_context: "off" | "home" | "game" | "both";
  controller_alerts_enabled: boolean;
  controller_connect_enabled: boolean;
  controller_low_enabled: boolean;
  controller_charging_enabled: boolean;
  controller_low_threshold: number;
  controller_connect_variant: string;
  controller_persistent_variant: string;
  controller_low_variant: string;
  controller_charging_variant: string;
  controller_duo_variant: string;
  controller_colour_preset: "automatic" | "manual";
  controller_colour_mode: "battery" | "players";
  controller_colour_normal: RGB;
  controller_colour_medium: RGB;
  controller_colour_low: RGB;
  controller_colour_charging: RGB;
  controller_player_colour_1: RGB;
  controller_player_colour_2: RGB;
  controller_player_colour_3: RGB;
  controller_player_colour_4: RGB;
  controller_gauge_brightness: number;
  weather_display: "off" | "home" | "game" | "everywhere";
  weather_location: WeatherLocation | null;
  weather_topbar_enabled: boolean;
  weather_icon_style: WeatherIconStyle;
  weather_temperature_unit: "celsius" | "fahrenheit";
  night_mode_enabled: boolean;
  night_mode_brightness: number;
  night_mode: {
    enabled: boolean;
    active: boolean;
    available: boolean;
    location: WeatherLocation | null;
    is_night: boolean | null;
    sunrise_at: string;
    sunset_at: string;
    next_transition_at: string;
    brightness: number;
  };
  weather_brightness: number;
  weather_shadow_cutoff: number;
  stripmine_integration_enabled: boolean;
  stripmine_detected: boolean;
  tw3_steamrgb_integration_enabled: boolean;
  tw3_steamrgb_detected: boolean;
  tw3_steamrgb_active: boolean;
  stripmine_priority_artwork: CompanionPriority;
  stripmine_priority_performance: CompanionPriority;
  stripmine_priority_weather: CompanionPriority;
  stripmine_priority_controller: CompanionPriority;
  stripmine_priority_light_events: CompanionPriority;
  stripmine_priority_game_launches: CompanionPriority;
  stripmine_priority_customization: CompanionPriority;
  stripmine_priority_screen_sync: CompanionPriority;
  stripmine_priority_audio_sync: CompanionPriority;
  weather_clear_day_variant: number;
  weather_clear_night_variant: number;
  weather_rain_variant: number;
  weather_cloud_variant: number;
  weather_cloud_night_variant: number;
  weather_breaks_variant: number;
  weather_breaks_night_variant: number;
  weather_snow_variant: number;
  weather_storm_variant: number;
  weather: {
    location: WeatherLocation | null;
    display: Status["weather_display"];
    phase: "off" | "waiting" | "loading" | "ready" | "error";
    error: string;
    temperature_c: number | null;
    condition: WeatherCondition | null;
    is_day: boolean | null;
    weather_code: number | null;
    observed_at: string;
    sunrise_at: string;
    sunset_at: string;
    next_solar_transition_at: string;
    night_mode_enabled: boolean;
    night_mode_active: boolean;
    night_mode_brightness: number;
    age_s: number | null;
    preview_active: boolean;
    preview_remaining_s: number;
    colors: RGB[];
    active_here: boolean;
  };
  controllers: {
    controllers: { id: string; name: string; percent: number | null; level: number | null; charging: boolean | null }[];
    active: boolean;
    kind: string;
    variant: string;
    colors: RGB[];
    persistent_available: boolean;
    charging_active: boolean;
  };
  events: {
    active: boolean;
    kind: string;
    variant: string;
    recording: boolean;
    queued: number;
    colors: RGB[];
  };
  game: { appid: number; title: string };
  performance: {
    sample_age_s: number | null;
    error: string;
    gpu_load: number | null;
    gpu_temperature: number | null;
    cpu_load: number | null;
    cpu_temperature: number | null;
    logical_lit: number;
    physical_lit: number;
  };
  thermal_protection: {
    active: boolean;
    message: string;
    trip_temperature_c: number;
    reset_temperature_c: number;
    reset_hold_seconds: number;
    recovery_remaining_s: number | null;
    trigger_sensor: string;
    triggered_at: number;
    cpu_temperature: number | null;
    gpu_temperature: number | null;
    sensor_state: "waiting" | "unavailable" | "ok" | "hot" | "cooling" | "recovering" | "fail-safe";
  };
  artwork: { sample_y?: number; filename?: string; colors?: RGB[]; dominant_colors?: RGB[] };
  launch_artwork: {
    active: boolean;
    paused: boolean;
    pending: boolean;
    pattern: LaunchArtworkPattern;
    duration_seconds: number;
    remaining_seconds: number;
    colour_count: 2 | 3;
    dominant_colors: RGB[];
    colors: RGB[];
  };
  customization: {
    calibration_preview_active: boolean;
    calibration_stage: "idle" | "colour-separation" | "white-balance" | "motion-contrast";
    calibration_remaining_s: number;
    preview_active: boolean;
    brightness_preview_active: boolean;
    brightness_preview_mode: "day" | "night";
    brightness_preview_remaining_s: number;
    colors: RGB[];
  };
  screen_sync: {
    revision: string;
    active: boolean;
    phase: "off" | "waiting" | "capturing" | "conflict" | "error";
    error: string;
    node_id: number | null;
    node_name: string;
    runtime_dir: string;
    capture_identity: string;
    discovery_detail: string;
    capture_selector: string;
    stderr_tail: string[];
    conflicting_consumers: number;
    frame_age_s: number | null;
    frames_per_second: number;
    orphan_processes_cleaned: number;
    capture_sessions_released: number;
    last_release_error: string;
    crop_top: number;
    crop_bottom: number;
    colors: RGB[];
    fallback_active: boolean;
    fallback_reason: string;
    activation: {
      requested: boolean;
      reason: "" | "game-route" | "steam-screensaver" | "manual-preview";
      preview_remaining_s: number;
      screensaver_active: boolean;
      screensaver_lease_remaining_s: number;
      screensaver_detection: "waiting" | "available" | "unavailable" | "error";
      screensaver_detail: string;
    };
  };
  audio_sync: {
    revision: string;
    active: boolean;
    phase: "off" | "capturing" | "error";
    error: string;
    runtime_dir: string;
    capture_identity: string;
    source: string;
    sample_rate: number;
    channels: number;
    frame_age_s: number | null;
    blocks_per_second: number;
    capture_latency_ms: number;
    analysis_window_ms: number;
    analysis_hop_ms: number;
    target_blocks_per_second: number;
    led_request_interval_ms: number;
    led_render_floor_ms: number;
    buffered_ms: number;
    queued_blocks: number;
    dropped_blocks: number;
    stderr_tail: string[];
    preview_active: boolean;
    preview_remaining_s: number;
    colors: RGB[];
    levels: number[];
    left_level: number;
    right_level: number;
    screen_palette: RGB[];
    palette_source: "selected" | "screen-sync" | "artwork" | "held-transition" | "sapphire-fallback";
    hifi_metrics: {
      impact: number;
      attack: number;
      texture: number;
      stereo: number;
      window_s: number;
    };
    response_timing: {
      reactivity: "calm" | "balanced" | "fast" | "punchy";
      level: { rise_ms: number; fall_ms: number };
      impact: { rise_ms: number; fall_ms: number };
      attack: { rise_ms: number; fall_ms: number };
      texture: { rise_ms: number; fall_ms: number };
      background: { rise_ms: number; fall_ms: number };
      crest: { cooldown_ms: number; centre_to_edge_ms: number; lifetime_ms: number };
    };
  };
  countdown: {
    active: boolean;
    source: "" | "parental" | "free" | "preview";
    label: string;
    remaining_seconds: number;
    total_seconds: number;
    scale_seconds: number;
    alerting: boolean;
    logical_lit: number;
    physical_lit: number;
    colors: RGB[];
  };
  debug: {
    led_path: string;
    last_write: number;
    last_write_age_s: number | null;
    writes: number;
    last_external: number;
    last_external_age_s: number | null;
    cooldown_remaining: number;
    stable_remaining: number;
    guard_state: "ready" | "blocked";
    guard_reason: string;
    steam_priority: boolean;
    steam_priority_reason: string;
    guard_hard_priority: boolean;
    guard_hard_reason: string;
    native_priority_kind: "" | "effect";
    native_priority_reason: string;
    ignored_native_takeovers: number;
    steam_led_override_state: "waiting" | "blocked" | "download" | "inactive" | "unavailable" | "error" | string;
    steam_lease_remaining_s: number;
    launch_handoff_remaining_s: number;
    context_transition_active: boolean;
    context_transition_remaining_s: number;
    context_transition_from: number;
    context_transition_to: number;
    last_recovery_age_s: number | null;
    last_recovery_reason: string;
    reverse_led_order: boolean;
    engine_running: boolean;
    decision_age_s: number | null;
    last_runtime_error: string;
    last_runtime_error_age_s: number | null;
    appid: number;
    game_detection_source: string;
    game_sync_ms: number | null;
    game_session_state: string;
    game_retained_count: number;
    frontend_heartbeat_age_s: number | null;
    parental_callback_state: "idle" | "disabled" | "waiting" | "received";
    parental_callback_delay_ms: number | null;
    parental_wait_s: number | null;
    controller_callback_source: string;
    controller_last_update_age_s: number | null;
    controller_telemetry: import("./controller_monitor").ControllerTelemetry;
  };
}

export interface ArtworkPayload {
  found: boolean;
  appid: number;
  mime?: string;
  filename?: string;
  fingerprint?: string;
  data_uri?: string;
  cached?: boolean;
  source?: ArtworkSource;
  source_label?: string;
}
